classbased/urls.py
from django.urls import path
from .views import FirstTemplate, FirstTemplateRedirect, FirstView, TemplateView
from .crud_views import Create, List, Detail, Update, Delete
app_name = 'classbased'
urlpatterns = [
    # classbased
    path('first/', FirstView.as_view()),
    path('first-test/', FirstTemplate.as_view()),
    path('template-redirect/', FirstTemplateRedirect.as_view()),
    path('create/', Create.as_view(), name='create'),
    path('list/', List.as_view(), name='list'),
    path('detail/<int:id>', Detail.as_view(), name='detail'),
    path('update/<int:id>', Update.as_view(), name='update'),
    path('delete/<int:pk>', Delete.as_view(), name='delete'),


]

crud/urls.py
from django.urls import path
from .views import delete_user_info, list_all_user, detail_view, create_user_info, update_user_info

app_name = 'crud'
urlpatterns = [
    # curd
    path('list/', list_all_user, name='list'),
    path('detail/<int:user_id>', detail_view, name='detail'),
    path('create/', create_user_info, name='create'),
    path('update/<int:user_id>', update_user_info, name='update'),
    path('delete/<int:user_id>', delete_user_info, name='delete')

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('', forms_home),
    path('admin/', admin.site.urls),
    path('forms/', include('forms_practice.urls')),
    path('rest/', include('rest.urls')),
    path('static-demo/', include('static_media.urls')),
    path('api/', include('rest_class.urls')),
    path('crud/', include('crud.urls', namespace='crud'), ),
    path('classbased/', include('classbased.urls', namespace='classbased')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

if settings.DEBUG:
    urlpatterns += static('settings.MEDIA_URL',
                          document_root='settings.MEDIA_ROOT')

classbased/models.py
from django.db import models

# Create your models here.


class UserInfo(models.Model):
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    dob = models.DateField()
    bio = models.TextField()

    def __str__(self):
        return self.email

classbased/forms.py
from django.db.models import fields
from django.forms import ModelForm

from .models import UserInfo


class UserInfoModelForm(ModelForm):
    class Meta:
        model = UserInfo
        fields = ['first_name', 'middle_name',
                  'last_name', 'email', 'dob', 'bio']

classbased/views.py
# from django.shortcuts import render
from django.http.response import HttpResponse
from django.views import View
from django.views.generic import TemplateView, RedirectView

# Create your views here.


class FirstView(View):
    # get
    # post method --> post()

    def get(self, request, *args, **kwargs):
        return HttpResponse("This is Get")

    def post(self, request, *args, **kwargs):
        return HttpResponse("This is POST")


class FirstTemplate(TemplateView):
    template_name = 'classbased/test.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "Hello World"
        return context


class FirstTemplateRedirect(RedirectView):
    url = '/classbased/first-test/'

classbased/templates/classbased/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Crete User</title>
    </head>
    <body>
        <h1>Create a new User Form</h1>
        <form method="POST" action="">
            <!-- token -->
            {% csrf_token %}
            <!-- django form -->
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </body>
</html>

classbased/templates/classbased/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <h1>Detail of User</h1>
        <article>
            <h4><span>First Name: </span> <em>{{data.first_name}}</em></h4>
            {% if data.middle_name %}
            <h4><span>Middle Name:</span> {{data.middle_name}}<em</em></h4>
            {% else %}
            <h4><span>Middle Name:</span> -<em</em></h4>
            {% endif %}
            <h4><span>Last Name</span> <em>{{data.last_name}}</em></h4>
            <h4><span>Email</span> <em>{{data.email}}</em></h4>
        </article>
    </body>
</html>

classbased/templates/classbased/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>User Info List</title>
        <style>
            table {
                width: 100%;
                text-align: center;
            }
            td,
            th {
                padding: 8px 12px;
            }
            tr:nth-child(2n) {
                background-color: #efefef;
            }
        </style>
    </head>
    <body>
        <h1>List of all Users</h1>
        <!-- {{object_list}} -->
        <button><a href="{% url 'classbased:create' %}">Create New</a></button>
        <table>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email</th>
            </tr>

            {% for item in data %}
            <tr>
                <td>{{item.id}}</td>
                <td>{{item.first_name}}</td>
                {% if not item.middle_name %}
                <td>-</td>
                {% else %}
                <td>{{item.middle_name}}</td>
                {% endif %}
                <td>{{item.last_name}}</td>
                <td>{{item.email}}</td>
                <td>
                    <a href="{% url 'classbased:detail' item.id %}">Details</a>/
                    <a href="{% url 'classbased:update' item.id %}">Update</a>/
                    <!-- <a href="{% url 'classbased:delete' item.id %}">Delete</a> -->
                    <form
                        action="/classbased/delete/{{item.id}}"
                        method="post"
                        id="form-delete"
                    >
                        {% csrf_token %}
                        <a
                            href="#"
                            onclick="document.getElementById('form-delete').submit()"
                            >Delete
                        </a>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

classbased/templates/classbased/test.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <h1>{{msg}}</h1>
    </body>
</html>

classbased/templates/classbased/update.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Crete User</title>
    </head>
    <body>
        <h1>Create a new User Form</h1>
        <form method="POST" action="">
            <!-- token -->
            {% csrf_token %}
            <!-- django form -->
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </body>
</html>