crud/urls.py
from django.urls import path
from .views import delete_user_info, list_all_user, detail_view, create_user_info, update_user_info

app_name = 'crud'
urlpatterns = [
    # curd
    path('list/', list_all_user, name='list'),
    path('detail/<int:user_id>', detail_view, name='detail'),
    path('create/', create_user_info, name='create'),
    path('update/<int:user_id>', update_user_info, name='update'),
    path('delete/<int:user_id>', delete_user_info, name='delete')

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('', forms_home),
    path('admin/', admin.site.urls),
    path('forms/', include('forms_practice.urls')),
    path('rest/', include('rest.urls')),
    path('static-demo/', include('static_media.urls')),
    path('api/', include('rest_class.urls')),
    path('crud/', include('crud.urls', namespace='crud'), ),
    path('classbased/', include('classbased.urls', namespace='classbased')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

if settings.DEBUG:
    urlpatterns += static('settings.MEDIA_URL',
                          document_root='settings.MEDIA_ROOT')

crud/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import UserInfo

# Form
from .forms import UserInfoModelForm
# Create your views here.


def list_all_user(request):
    all_users = UserInfo.objects.all()
    # print(all_users)
    context = {
        'data': all_users
    }
    return render(request, './crud/list.html', context=context)


def detail_view(request, user_id):
    # try:
    #     data = UserInfo.objects.get(id=user_id)
    # except:
    #     raise Exception("User doesn\'t Exists")
    data = get_object_or_404(UserInfo, id=user_id)
    context = {
        'data': data
    }
    return render(request, 'crud/detail.html', context=context)


def create_user_info(request):

    if request.method == 'POST':

        form = UserInfoModelForm(request.POST)
        if form.is_valid():
            print(form.changed_data)
            print("form is valid")
            form.save()
            return redirect('/crud/list')
        else:
            print("Invalid Form")
    else:
        form = UserInfoModelForm()
    context = {
        'form': form
    }
    return render(request, './crud/create.html', context=context)


def update_user_info(request, user_id):
    user_object = get_object_or_404(UserInfo, id=user_id)
    if request.method == 'POST':

        form = UserInfoModelForm(request.POST, instance=user_object)
        if form.is_valid():
            print(form.changed_data)
            print("form is valid")
            form.save()
            return redirect(f'/crud/detail/{user_id}')
        else:
            print("Invalid Form")
    else:
        form = UserInfoModelForm(instance=user_object)
    context = {
        'form': form
    }
    return render(request, './crud/update.html', context=context)


def delete_user_info(request, user_id):
    if request.method == 'GET':
        user_object = get_object_or_404(UserInfo, id=user_id)
        user_object.delete()
    return redirect('/crud/list')

crud/templates/crud/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>User Info List</title>
        <style>
            table {
                width: 100%;
                text-align: center;
            }
            td,
            th {
                padding: 8px 12px;
            }
            tr:nth-child(2n) {
                background-color: #efefef;
            }
        </style>
    </head>
    <body>
        <h1>List of all Users</h1>
        <button><a href="{% url 'crud:create' %}">Create New</a></button>
        <table>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email</th>
            </tr>
            {% for item in data %}
            <tr>
                <td>{{item.id}}</td>
                <td>{{item.first_name}}</td>
                {% if not item.middle_name %}
                <td>-</td>
                {% else %}
                <td>{{item.middle_name}}</td>
                {% endif %}
                <td>{{item.last_name}}</td>
                <td>{{item.email}}</td>
                <td>
                    <a href="{% url 'crud:detail' item.id %}">Details</a>/
                    <a href="{% url 'crud:update' item.id %}">Update</a>/
                    <a href="{% url 'crud:delete' item.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>